# -*- coding: utf-8 -*-
{
    'name': 'Pragmatic Approve Hub Invoice',
    'version': '16.0.4',
    'category': 'Services',
    'author': 'Pragmatic TechSoft Pvt Ltd.',
    'website': 'http://pragtech.co.in',
    'summary': 'Pragmatic Approve Hub Invoice',
    'description': 'Pragmatic Approve Hub Invoice',
    'depends': ['base', 'pragtech_approval_hub', 'mail', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
        'views/account_move_views.xml',
        'data/submit_invoice_template.xml',
        'data/approve_invoice_template.xml',
        'data/reject_invoice_template.xml',
        'wizard/RejectionReasonWizard.xml',
    ],
    'demo': ['demo/demo.xml'],
    'images': ['static/description/approve_hub_invoicing.gif'],
    'live_test_url': 'http://www.pragtech.co.in/company/proposal-form.html?id=103&name=Pragmatic-Approve-Hub',
    'currency': 'USD',
    'price': 79,
    'license': 'OPL-1',
    'installable': True,
    'application': False,
    'auto_install': False,
}
